name: MSBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Windows SDK
      uses: microsoft/setup-windowsdriver-build-tools@v1
      with:
        wdk-version: '10.0.22621.0'  # 使用最新的 WDK 版本

    - name: Build Solution
      run: |
        msbuild /m /p:Configuration=Release /p:Platform=x64 ItsNotASecurityBoundary.sln

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: |
          x64/Release/*.exe
          x64/Release/*.dll
          x64/Release/*.sys 
